/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.layersmvc.presentacion;

import co.edu.unicauca.layersmvc.access.CompanyRepository;
import co.edu.unicauca.layersmvc.access.ICompanyRepository;
import co.edu.unicauca.layersmvc.access.IProjectRepository;
import co.edu.unicauca.layersmvc.access.IStudentRepository;
import co.edu.unicauca.layersmvc.access.ProjectRepository;
import co.edu.unicauca.layersmvc.access.StudentRepository;
import co.edu.unicauca.layersmvc.domain.Project;
import co.edu.unicauca.layersmvc.domain.Project.ProjectState;

import co.edu.unicauca.layersmvc.domain.User;
import co.edu.unicauca.layersmvc.domain.service.ServiceCompany;
import co.edu.unicauca.layersmvc.domain.service.ServiceProject;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Katherine
 */
public class GUICompanyView extends javax.swing.JFrame {

private ServiceProject serviceProject;
    private ServiceCompany serviceCompany;
    private ArrayList<Project> projectList;
    /**
     * Creates new form GUIACompanyView
     */
    public GUICompanyView(ServiceProject serviceProject, ServiceCompany serviceCompany) {
    this.serviceProject = serviceProject;
    this.serviceCompany = serviceCompany;
    this.projectList = new ArrayList<>();
    
    initComponents();  // Inicializa los componentes gráficos (incluida jTable1)
    
    actualizarTabla();  // Ahora se llama después de la inicialización de los componentes
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextNombreEm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextnombrePro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextObjetivos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextdescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTexttiempoMax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextpresupuesto = new javax.swing.JTextField();
        GuardarProyecto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextidPro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jestadoProyecto = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablemisproyectosEditable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonSalirCompany = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nit Compañia:");

        jLabel2.setText("Nombre Empresa:");

        jLabel3.setText("Nombre Proyecto:");

        jLabel4.setText("Objetivos:");

        jLabel5.setText("Descripción:");

        jLabel6.setText("Tiempo Maximo");

        jLabel7.setText("Presupuesto:");

        GuardarProyecto.setText("Guardar");
        GuardarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProyectoActionPerformed(evt);
            }
        });

        jLabel8.setText("Id Proyecto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(GuardarProyecto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombreEm, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jTextNit)
                            .addComponent(jTextidPro)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextnombrePro)
                            .addComponent(jTextObjetivos)
                            .addComponent(jTextdescripcion)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextpresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTexttiempoMax))))
                .addGap(40, 679, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextidPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombreEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextnombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextObjetivos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTexttiempoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTextpresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(GuardarProyecto)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Proyecto", jPanel2);

        jestadoProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Proyecto", "Estado", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jestadoProyecto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(172, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Estado", jPanel3);

        jTablemisproyectosEditable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Proyecto", "Nit", "Empresa", "Proyecto", "Objetivos", "Descripción", "Tiempo Max", "Presupuesto", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablemisproyectosEditable);

        jButton1.setText("Editar");

        jButton2.setText("Dar de baja");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton2)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(374, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mis Proyectos", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSalirCompany.setText("Salir");
        jButtonSalirCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirCompanyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalirCompany)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonSalirCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProyectoActionPerformed
     if (!validarCampos()) {
        return;
    }
    
    // Obtener los valores de los campos de texto
    int id = Integer.parseInt(jTextidPro.getText());
    int companyNit = Integer.parseInt(jTextNit.getText());
    String nombreEmpresa = jTextNombreEm.getText();
    String nombreProyecto = jTextnombrePro.getText();
    String objetivos = jTextObjetivos.getText();
    String descripcion = jTextdescripcion.getText();
    String tiempoMax = jTexttiempoMax.getText();
    Double presupuesto = Double.parseDouble(jTextpresupuesto.getText());
    
    // Crear el estado del proyecto (puedes ajustarlo según lo necesites)
    ProjectState estado = ProjectState.PROPUESTO;  // Asumiendo que el estado es INICIADO al principio

    // Crear una nueva instancia de Project, pasando todos los parámetros
    Project newProject = new Project(id,companyNit, nombreEmpresa, nombreProyecto, 
                                      objetivos, descripcion, tiempoMax, presupuesto, estado);

    // Usar el servicio para guardar el proyecto
    boolean resultado = serviceProject.saveProject(newProject);
    
    if (resultado) {
        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Proyecto guardado exitosamente.");
    } else {
        // Mostrar mensaje de error
        JOptionPane.showMessageDialog(this, "Error al guardar el proyecto.");
    }

    // Limpiar los campos de texto
    limpiarCampos();

    // Actualizar la tabla
    actualizarTabla();
   
    }//GEN-LAST:event_GuardarProyectoActionPerformed

    private void jButtonSalirCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirCompanyActionPerformed
       GUIUserView login = new GUIUserView();

        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonSalirCompanyActionPerformed
private void actualizarTabla() {
    List<Project> proyectos = serviceProject.listProjects();
    DefaultTableModel model = (DefaultTableModel) jTablemisproyectosEditable.getModel();

    
    
    // Limpiar la tabla antes de agregar nuevos datos
    model.setRowCount(0);
    
    // Añadir filas de proyectos
    for (Project proyecto : proyectos) {
        model.addRow(new Object[]{
            proyecto.getId(),
            proyecto.getCompanyNit(),
            proyecto.getNombreEmpresa(),
            proyecto.getNombreProyecto(),
            proyecto.getObjetivos(),
            proyecto.getDescripcion(),
            proyecto.getTiempoMax(),
            proyecto.getPresupuesto()
        });
    }
}


private void limpiarCampos() {
    jTextidPro.setText("");
    jTextNit.setText("");  
    jTextNombreEm.setText("");  
    jTextnombrePro.setText("");  
    jTextObjetivos.setText("");  
    jTextdescripcion.setText("");  
    jTexttiempoMax.setText("");  
    jTextpresupuesto.setText("");  
}

private boolean validarCampos() {
    if ( jTextNit.getText().isEmpty() || jTextNombreEm.getText().isEmpty() ||
        jTextnombrePro.getText().isEmpty() || jTextObjetivos.getText().isEmpty() ||
        jTextdescripcion.getText().isEmpty() || jTexttiempoMax.getText().isEmpty() ||
        jTextpresupuesto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser llenados.");
            return false;
    }

    try {
        Integer.parseInt(jTextNit.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El NIT debe ser un número válido.");
        return false;
    }

    try {
        Double.parseDouble(jTextpresupuesto.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El presupuesto debe ser un número válido.");
        return false;
    }

    return true;
}



    /**
     * @param args the command line arguments
     */
   public static void main(String[] args) {
    // Crear los repositorios necesarios
    IProjectRepository projectRepository = new ProjectRepository();  
    IStudentRepository studentRepository = new StudentRepository();  
    ICompanyRepository companyRepository = new CompanyRepository();  // Crear el repositorio de empresas

    // Crear los servicios necesarios
    ServiceProject serviceProject = new ServiceProject(projectRepository, studentRepository);
    ServiceCompany serviceCompany = new ServiceCompany(companyRepository); // Pasar el repositorio de empresas al servicio

    // Crear la vista de la empresa pasando el servicio adecuado
    GUICompanyView view = new GUICompanyView(serviceProject, serviceCompany);
    view.setVisible(true);

    // Actualizar la tabla para mostrar los proyectos registrados
    view.actualizarTabla();  // Llamar al método para llenar la tabla con los proyectos registrados
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarProyecto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSalirCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablemisproyectosEditable;
    private javax.swing.JTextField jTextNit;
    private javax.swing.JTextField jTextNombreEm;
    private javax.swing.JTextField jTextObjetivos;
    private javax.swing.JTextField jTextdescripcion;
    private javax.swing.JTextField jTextidPro;
    private javax.swing.JTextField jTextnombrePro;
    private javax.swing.JTextField jTextpresupuesto;
    private javax.swing.JTextField jTexttiempoMax;
    private javax.swing.JTable jestadoProyecto;
    // End of variables declaration//GEN-END:variables

   

}
