/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.layersmvc.presentacion;

import co.edu.unicauca.layersmvc.access.IProjectRepository;
import co.edu.unicauca.layersmvc.access.IStudentRepository;
import co.edu.unicauca.layersmvc.access.ProjectRepository;
import co.edu.unicauca.layersmvc.access.StudentRepository;
import co.edu.unicauca.layersmvc.domain.Project;
import co.edu.unicauca.layersmvc.domain.Student;
import co.edu.unicauca.layersmvc.domain.User;
import co.edu.unicauca.layersmvc.domain.Role;
import co.edu.unicauca.layersmvc.domain.Student.StudentState;
import co.edu.unicauca.layersmvc.domain.service.ServiceProject;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Katherine
 */
public class GUIStudentView extends javax.swing.JFrame {
private List<Project> projects;
    private Student currentStudent;
    private IProjectRepository projectRepository;
    private IStudentRepository studentRepository;

    public GUIStudentView(List<Project> projects, Student currentStudent, IProjectRepository projectRepository, IStudentRepository studentRepository) {
        initComponents();
        this.projects = projects;
        this.currentStudent = currentStudent;
        this.projectRepository = projectRepository;
        this.studentRepository = studentRepository;
        loadProjects();
        loadMyProjects();
    }

    public Student getCurrentStudent() {
        return this.currentStudent;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproyectosES = new javax.swing.JTable();
        jButtonpostularse = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablemisproyectosEs = new javax.swing.JTable();
        jButtonSalirEs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableproyectosES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Proyecto", "Empresa", "Proyecto", "Objetivos", "Descripción", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableproyectosES);

        jButtonpostularse.setText("Postularse");
        jButtonpostularse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpostularseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonpostularse)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButtonpostularse))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proyectos", jPanel2);

        jTablemisproyectosEs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Empresa", "Proyecto", "Objetivos", "Descripción", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablemisproyectosEs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mis Proyectos", jPanel3);

        jButtonSalirEs.setText("Salir");
        jButtonSalirEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirEsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalirEs, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonSalirEs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonpostularseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpostularseActionPerformed
     int selectedRow = jTableproyectosES.getSelectedRow();
        if (selectedRow >= 0) {
           
            int projectId = (int) jTableproyectosES.getValueAt(selectedRow, 0);
            int studentId = currentStudent.getIdentificacion();

            ServiceProject serviceProject = new ServiceProject(projectRepository, studentRepository);
            boolean success = serviceProject.postularEstudianteAProyecto(studentId, projectId);

            if (success) {
                JOptionPane.showMessageDialog(this, "Postulación exitosa!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                loadMyProjects(); 
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo realizar la postulación.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un proyecto para postularse.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonpostularseActionPerformed

    private void jButtonSalirEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirEsActionPerformed
      GUIUserView login = new GUIUserView();

        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonSalirEsActionPerformed
private void loadProjects() {
        DefaultTableModel model = (DefaultTableModel) jTableproyectosES.getModel();
        model.setRowCount(0); // Limpiar la tabla

        this.projects = projectRepository.list(); // Obtener lista actualizada

        for (Project p : this.projects) {
            model.addRow(new Object[]{
                p.getId(),          // ✅ Ahora se muestra el ID correcto
                p.getNombreEmpresa(),
                p.getNombreProyecto(),
                p.getObjetivos(),
                p.getDescripcion(),
                p.getEstado()
            });
        }
    }

private void loadMyProjects() {
    DefaultTableModel model = (DefaultTableModel) jTablemisproyectosEs.getModel();
    model.setRowCount(0); // Limpiar la tabla

    ServiceProject serviceProject = new ServiceProject(projectRepository, studentRepository);
    List<Project> myProjects = serviceProject.getProjectsByStudent(currentStudent.getIdentificacion());

    for (Project p : myProjects) {
        model.addRow(new Object[]{
            p.getNombreEmpresa(),
            p.getNombreProyecto(),
            p.getObjetivos(),
            p.getDescripcion(),
            p.getEstado()
        });
    }
}


private void showProjectDetails(Project project) {
        String message = "Objetivos: " + project.getObjetivos() + "\nEstado: " + project.getEstado();
        JOptionPane.showMessageDialog(this, message, "Detalles del Proyecto", JOptionPane.INFORMATION_MESSAGE);
    }

    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        IProjectRepository projectRepository = new ProjectRepository();
        IStudentRepository studentRepository = new StudentRepository();

        ServiceProject serviceProject = new ServiceProject(projectRepository, studentRepository);
        List<Project> projectList = serviceProject.listProjects();

        // Crear y registrar un estudiante antes de abrir la GUI
        Student currentStudent = new Student(12345, "Juan", "Perez",  "j@correo", "", "");
        studentRepository.save(currentStudent);

        new GUIStudentView(projectList, currentStudent, projectRepository, studentRepository).setVisible(true);
    });
}

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalirEs;
    private javax.swing.JButton jButtonpostularse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablemisproyectosEs;
    private javax.swing.JTable jTableproyectosES;
    // End of variables declaration//GEN-END:variables
}
